name: "Sap BTP CF CLI Action - Build and Deploy"
description: "Deploy and build sapui5/nodejs app in Cloud Foundry Runtime using the cf cli"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  cf_api:
    description: "Target API Endpoint of Cloud Foundry"
    required: true
  cf_username:
    description: "Username for API authentication"
    required: true
  cf_password:
    description: "Password for API authentication"
    required: true
  cf_org:
    description: "Target Organization"
    required: false
  cf_space:
    description: "Target Space"
    required: false
  build_command:
    description: "Command to run using CF CLI Build"
    required: true
  deploy_command:
    description: "Command to run using CF CLI Deploy"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - name: Install MTA Build Tool
      run: npm install -g mbt
    - name: Build MTA
      run: mbt build -p cf --mtar project.mtar
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: mta
        path: ./mta_archives/project.mtar
    - name: Cloud Foundry deploy
    - uses: "docker"
    - image: "Dockerfile"
    - args:
      - ${{ inputs.build_command }}